### PR TITLE
Update binary output version strings to YYYY-MM-DD convention

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
Updates version strings (`VERxxx` variable) in output binary files to use a consistent YYYY-MM-DD convention.

I have chosen the last update date from the top level change history as the new version string value for each file.

Related issue: #152

One downside to this change is that it obviously has a massive impact on the regtests as every binary file will be different (due to the header change). I am hoping that in this case, the change is small enough that a simple code review will be sufficient?

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
@JessicaMeixner-NOAA - would you be able to review?

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney I'd be happy to review as long as it's okay it's not today or tomorrow. I'm not sure what your needed turn around time for this is?

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney I'd be happy to review as long as it's okay it's not today or tomorrow. 

Thanks @JessicaMeixner-NOAA. No rush on this one - slow time is fine :)

**Review by ukmo-ansaulter — APPROVED** [review]
If Jessica and others are comfortable with using the date identifier (I have no strong opinion), I'm perfectly happy with these changes. Andy

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Looks good to me.   I like it being consistent throughout all the VER* options.  

My only additional suggestion is we should add these files and others to the list here https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop which only includes the "If w3iogrmd.ftn was updated, did you update VERGRD?" as of now.

**Comment by ukmo-ccbunney** [comment]
> My only additional suggestion is we should add these files and others to the list here https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop

Agreed. Do you know if I can make a PR for updating the Wiki? I can clone it, but don't see a mechanism for updating it.

**Comment by JessicaMeixner-NOAA** [comment]
> > My only additional suggestion is we should add these files and others to the list here https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop
> 
> Agreed. Do you know if I can make a PR for updating the Wiki? I can clone it, but don't see a mechanism for updating it.

My quick googling says no.  Maybe just make an issue with the desired wiki updates?   @ajhenrique @Ali.Abdolali Do you have another suggestion for those who want to make updates to wiki that do not have write access?

**Comment by ukmo-ccbunney** [comment]
> My only additional suggestion is we should add these files and others to the list here https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop which only includes the "If w3iogrmd.ftn was updated, did you update VERGRD?" as of now.

This has been done directly via Ali.

**Comment by ukmo-ccbunney** [comment]
This PR will now be performed directly on the NOAA repo; new PR raised here https://github.com/NOAA-EMC/WW3/pull/182.

Closing this PR.

**Pull request closed without merging**
