### PR TITLE
WW3_OUNF updates 

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
# Pull Request Summary
Two small updates to `ww3_ounf`.

## Description
Provides two new optional inputs in the `ww3_ounf.nml` namelist file.
  - `FIELD%NOVAL` : Defines a value to be used for sea points that have a value of UNDEF (such as in partitioned outputs). This helps to differentiate between land and sea points with no value. Required for CMEMS netCDF files. See example screenshot below. Defaults to `UNDEF` so current behaviour is maintained.
  - `FIELD%MAPSTA` : Logical to specift whether to create the `MAPSTA` variable in the output netCDF file. Defaults to `.TRUE.`

These values can only be set via the namelist file and are set the their defaults when using "inp" files.

### Issue(s) addressed
 n/a

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?
  * Yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop), [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
  * Done
* Reviewers: @mentions of suggested reviewers of the proposed changes.
  * @mickaelaccensi @aliabdolali 

### Testing
* How were these changes tested?
  * via the regression tests.
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
  * yes (for their default values)
* If a new feature was added, was a new regression test added?
  * `ww3_tnc1` modified to use `MAPSTA=.FALSE.` and `NOVAL=0.0`
* Have regression tests been run?
  * Yes - outputs attached,
* Which compiler / HPC you used to run the regression tests in the PR? 
  * Cray HPC, Gnu compiler.

### Results from regressions test:
Results attached here: [matrix_fb_ounfupd_run2.zip](https://github.com/ukmo-waves/WW3/files/6560055/matrix_fb_ounfupd_run2.zip)

**Summary:**
_Existing known differences:_
  - mww3_test_03/*
  - ww3_tp2.18/./work_TIDE_MPI

_Expected differences from this PR:_
  - In the following regtests, there will be a small difference in the `ww3_ounf.out` file stating that " MAPSTA output disabled for SMC grids":
    - ww3_tnc1/./work            
    - ww3_tp2.10/./work_MPI      
    - ww3_tp2.10/./work_MPI_OMPH 
    - ww3_tp2.14/./work_OASACM6  
    - ww3_tp2.16/./work_MPI
    - ww3_tp2.16/./work_MPI_OMPH 
  - The ww3_tnc1 regtest was updated to test `NOVAL=0.0` and `MAPSTA=F`, so the generated netCDF files are slightly different, but as expected.

All other regression tests are bit-for-bit.

### Screenshot:
Top pane shows NOVAL=0.0 compared to default behaviour in bottom pane.
Field is tertiary swell significant wave height.

noval

### CODE REVIEW

**Review by aliabdolali — COMMENTED** [review]
This is great, I like the idea.
Is there any regtests to check this feature and to check if some future development will not violate this option?

**Comment by ukmo-ccbunney** [comment]
> 
> 
> This is great, I like the idea.
> Is there any regtests to check this feature and to check if some future development will not violate this option?

Yes - I've updated `ww3_tnc1` to test both new features.

**Review by aliabdolali — APPROVED** [review]

**Comment by ukmo-ccbunney** [comment]
I'll wait for @mickaelaccensi's approval before merging this one.

**Comment by mickaelaccensi** [comment]
I've tested it and I found some issues :

-with both gnu and intel compilers, I had to set the CFL timestep in ww3_grid.nml to a value greater than 0 to avoid a crash with the following error message : 

```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7fffed5d9607 in ???
#1  0x7fffed5d886d in ???
#2  0x7fffecaf013f in ???
#3  0x51b75f in __w3initmd_MOD_w3init
	at /home7/datawork/devww3/UKMO_WW3/model/tmp/w3initmd.F90:597
#4  0x4161cd in w3shel
	at /home7/datawork/devww3/UKMO_WW3/model/tmp/ww3_shel.F90:1496
#5  0x4261d3 in main
	at /home7/datawork/devww3/UKMO_WW3/model/tmp/ww3_shel.F90:240

```

which is :
`        NTLOC  = 1 + INT(DTMAX/(DTCFL*SIG(IK)/SIG(1))-0.001)`


-with gnu compiler, I had to remove the statement "1000 FORMAT" in subroutine WRITE_META which is unused and since it contains the keyword ERROR, this line is then detected as an error..

then in subroutine WRITE_FREEFORM_META_LIST, I had to correct the call to WRITE statement as below : 

`         WRITE(1000,*) P%TYPE`
by
`         WRITE(NDSE,1000) P%TYPE`

Otherwise, your code modifications looks great to me but I would prefer if you could correct those problems also in this PR. If you prefer to assign them to another PR, let me know and I'll approve this PR.

**Comment by ukmo-ccbunney** [comment]
Thanks for spotting those @mickaelaccensi - I've pushed a commit that addresses the issues.

By the way - to avoid the "ERROR" strings being incorrectly picked up by the "comp" scripts when using the GNU compiler, I had to change the `err_pattern` and `warn_pattern` in `cmplr.env` to this when using GNU:

```
err_pattern='^error'
warn_pattern='^warn'
```

This ensures that the error and warn strings are matched only if they are at the beginning of the line (which is how the GNU compiler outputs them). I can make this change in this PR, if you like...

**Comment by mickaelaccensi** [comment]
ok it would be good to modify the cmplr.env for gnu

**Review by mickaelaccensi — APPROVED** [review]

**Comment by ukmo-ccbunney** [comment]
Commit 790f2d5 fixes NOAA-EMC/WW3#418 (false matching of compiler errors in generated comp script)

**Pull request merged**
