### PR TITLE
Backport of coupling update error fix from develop

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
# Pull Request Summary
Backport of coupling update error fix from the develop branch to the UKMO PS45 branch (hotfixes).

## Description
See: https://github.com/NOAA-EMC/WW3/pull/999

### CODE REVIEW

**Comment by ukmo-ccbunney** [comment]
@ukmo-juan-castillo - can you test on your coupled config please?

**Review by ukmo-juan-castillo — APPROVED** [review]
I can confirm that this works as expected.

**Comment by ukmo-ccbunney** [comment]
> I can confirm that this works as expected.

Great  - I'll merge and tag it in the ps45-1.hotfixes branch.
Thanks Juan.

**Comment by ukmo-ccbunney** [comment]
Tagged: https://github.com/ukmo-waves/WW3/releases/tag/ukmo_ps45-1.hotfix6

**Pull request merged**
