### PR TITLE
Add support for Intel compiler on Cray XC

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
# Pull Request Summary

## Description
Adds support for the Intel IFORT compiler to the `cmplr.env` script when running on the Cray XC HPC at the Met Office.
Adds two new compiler tags: `ukmo_cray_intel` and `ukmo_cray_intel_debug`.

The `matrix_ukmo_cray` matrix generation script has also been updated to add Met Office specific modules for the Intel compiler.

Note: I have deleted lines 187 - 195 of `cmplr.env` as they appear to be a duplicate of the section above (starting at line 141)

### Issue(s) addressed
n/a

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)? Yes
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop), [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
* Reviewers: @aliabdolali @mickaelaccensi 

### Testing
* How were these changes tested? **By running regression test matrix**
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) **No - is a change to build scripts**
* If a new feature was added, was a new regression test added? **N/A**
* Have regression tests been run? **Yes - but I don't have anything to compare against for the Intel compiler as this is a new feature. I have confirmed that the results are unchanged when using the existing GNU compiler**
* Which compiler / HPC you used to run the regression tests in the PR?  **Cray XC ,Cray Compiler Environment - Intel**

### CODE REVIEW

**Review by aliabdolali — APPROVED** [review]

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi  - are you happy with my deleting of lines 187 - 195 of cmplr.env (they are duplicated, as far as I can tell; see description)?

**Comment by mickaelaccensi** [comment]
right it was duplicated so you can remove one. But it would be clearer to keep the "system-dependent options" after the "debugging options" to keep the same structure for all compiler descriptions.

**Comment by ukmo-ccbunney** [comment]
> 
> 
> right it was duplicated so you can remove one. But it would be clearer to keep the "system-dependent options" after the "debugging options" to keep the same structure for all compiler descriptions.

Done - see latest commit.

**Review by mickaelaccensi — APPROVED** [review]

**Comment by ukmo-ccbunney** [comment]
Commit 9e85b29 fixes missing `||` operator in cmplr.env
Fixes: NOAA-EMC/WW3#415

**Pull request merged**
