### PR TITLE
Change coupling condition so that it works with all compilers

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
Fix for ticket NOAA-EMC#238

I tested the oasis coupling regtests with the gnu compiler (the modifications only affect these tests) and gives the same results as the original code. The cray compiler is working now, and when compared with the results using the gnu compiler there are some precision differences.

### CODE REVIEW

**Review by JessicaMeixner-NOAA — COMMENTED** [review]
I don't use OASIS coupling, so I don't know what ID_OASIS_TIME is to be a judge of if this is a good equivalent condition or not.  I'll defer to the other reviewers.

**Comment by mickaelaccensi** [comment]
ok for the new condition on ID_OASIS_TIME using NINT() instead of a small decimal value

**Review by ukmo-ccbunney — APPROVED** [review]
Looks like a sensible change to me.

**Comment by ukmo-ccbunney** [comment]
@ukmo-juan-castillo  - Can you attach the results of your regtests to this PR please?

**Comment by ukmo-juan-castillo** [comment]
Sorry for the delay, I had to run the regtests again.

[matrixCompSummary.txt](https://github.com/ukmo-waves/WW3/files/5195512/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/ukmo-waves/WW3/files/5195513/matrixDiff.txt)

**Comment by ukmo-ccbunney** [comment]
@ukmo-juan-castillo - matrix output looks OK to me (all differences are known issues).
@aliabdolali - are you happy with these changes?

**Review by aliabdolali — APPROVED** [review]
I am ok with the changes.

**Comment by ukmo-juan-castillo** [comment]
Thank you all

**Pull request merged**
