### PR TITLE
Bug fix and small simplification/optimization change

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
Branch fixing issue #290

The fix consist is changing one line in w3odatmd.ftn, the changes in w3iorsmd.ftn are simplification and optimization changes, that can be included here or in issue #207, I leave the reviewers to decide.

### CODE REVIEW

**Comment by ukmo-juan-castillo** [comment]
I will keep a draft status until I run the regtests.

**Comment by JessicaMeixner-NOAA** [comment]
I don't know if just the regression tests will be sufficient for testing this as I don't think we have a true "hot start" scenario in the regression tests where I think @mickaelaccensi was running into this issue.

**Comment by mickaelaccensi** [comment]
yes, a new test must be added in the regtests to confirm that the bug is fixed.

**Comment by ukmo-juan-castillo** [comment]
will be enough to just modify the mww3_test_04/input/ww3_multi_grdset_d.inp tests, or would you prefer a completely new test?

**Comment by mickaelaccensi** [comment]
for me, you can modify mww3_test_04/input/ww3_multi_grdset_d.inp and nml

**Comment by ukmo-juan-castillo** [comment]
I added the suggested test, which includes a test for issue #291, which I believe it can be close when the present ticket is closed. The regtests have finished and they look OK to me, I copy them here. I also copy the whole working directory of the new test.
[matrixDiff.tar.gz](https://github.com/ukmo-waves/WW3/files/5887233/matrixDiff.tar.gz)
[work_PR2_UNO_MPI_d.tar.gz](https://github.com/ukmo-waves/WW3/files/5887235/work_PR2_UNO_MPI_d.tar.gz)

**Review by ukmo-ccbunney — APPROVED** [review]
Well done on tracking down this bug @ukmo-juan-castillo - the change looks good to me. The optimisation of the MPI communication in w3iorsmd is a welcome addition too.

**Comment by ukmo-juan-castillo** [comment]
In fact a correction is needed, I realized yesterday. 

MPI_SEND_INIT calls are non-blocking. Therefore, we need to wait for completion with MPI_WAITALL after a call to MPI_STARTALL if the value that is sent can be modified before the send is complete, as the send buffer is shared and can be overwritten before the communication is complete. Having a look at the code indicates that this might be the case, as the variable that is sent (VA) is modified just after the MPI communication. It would make sense to delay or eliminate the MPI_WAITALL call only if the value of VA is modified at a later point or not at all. I do not expect the results to change because the problematic line is just:

A = MAX(0.,VA)

but if this is not corrected there is the possibility that the runs are not bit comparable.

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi - are you happy with this PR. Can I merge?

**Comment by mickaelaccensi** [comment]
Hi,

I've checked out your branch bf_multi_hang and I've run again the test mww3_test_04 with ww3_grdset_d.nml with a restart requested like described in issue #290. Could you confirm that you ran it with compiler **intel_debug** ?

I've still the following error in w3iorsmd.ftn : 

                              WRITEBUFF(1:NSPEC) = VAAUX(1:NSPEC,JSEA,IP)

see the logs below : 

  MWW3 calculating for 1968/06/06 02:00:00 UTC at 21:09:26  status [ 1- 5]
forrtl: severe (408): fort: (2): Subscript #2 of the array VAAUX has value 17 which is greater than the upper bound of 16

Image              PC                Routine            Line        Source             
ww3_multi          00000000015B1540  Unknown               Unknown  Unknown
ww3_multi          00000000012BE0F5  w3iorsmd_mp_w3ior         554  w3iorsmd.F90
ww3_multi          0000000000DAA809  w3wavemd_mp_w3wav        1413  w3wavemd.F90
ww3_multi          00000000008BA7CD  wmwavemd_mp_wmwav         871  wmwavemd.F90
ww3_multi          0000000000405363  MAIN__                    150  ww3_multi.F90
ww3_multi          000000000040461E  Unknown               Unknown  Unknown
libc-2.19.so       00002AAAAC647B25  __libc_start_main     Unknown  Unknown
ww3_multi          0000000000404529  Unknown               Unknown  Unknown
  MWW3 calculating for 1968/06/06 02:12:00 UTC at 21:09:26  status [ 1- 5]

**Comment by ukmo-juan-castillo** [comment]
> Hi,
> 
> I've checked out your branch bf_multi_hang and I've run again the test mww3_test_04 with ww3_grdset_d.nml with a restart requested like described in issue [NOAA-EMC#290](https://github.com/NOAA-EMC/WW3/issues/290). Could you confirm that you ran it with compiler **intel_debug** ?
> 
> I've still the following error in w3iorsmd.ftn :
> 
> ```
>                           WRITEBUFF(1:NSPEC) = VAAUX(1:NSPEC,JSEA,IP)
> ```
> 
> see the logs below :
> 
> MWW3 calculating for 1968/06/06 02:00:00 UTC at 21:09:26 status [ 1- 5]
> forrtl: severe (408): fort: (2): Subscript #2 of the array VAAUX has value 17 which is greater than the upper bound of 16
> 
> Image PC Routine Line Source
> ww3_multi 00000000015B1540 Unknown Unknown Unknown
> ww3_multi 00000000012BE0F5 w3iorsmd_mp_w3ior 554 w3iorsmd.F90
> ww3_multi 0000000000DAA809 w3wavemd_mp_w3wav 1413 w3wavemd.F90
> ww3_multi 00000000008BA7CD wmwavemd_mp_wmwav 871 wmwavemd.F90
> ww3_multi 0000000000405363 MAIN__ 150 ww3_multi.F90
> ww3_multi 000000000040461E Unknown Unknown Unknown
> libc-2.19.so 00002AAAAC647B25 __libc_start_main Unknown Unknown
> ww3_multi 0000000000404529 Unknown Unknown Unknown
> MWW3 calculating for 1968/06/06 02:12:00 UTC at 21:09:26 status [ 1- 5]

We are using the GNU compiler. I will have a look at your error, it should be easy to fix - just an out of bounds error.

**Comment by ukmo-juan-castillo** [comment]
Indeed it looks like there was another bug. I have changed the second index of VAAUX in the problematic line for what I think is the right index, and the problem disappears. Please double check.

**Comment by mickaelaccensi** [comment]
regtest passed ! thanks Juan. 
I think that it would be better for the next PR if you could run the regtests matrix with intel_debug to detect possible bugs which are not seen by gfortran

**Comment by ukmo-juan-castillo** [comment]
OK, I can try running next time in debug mode with the GNU or CRAY compiler, I do not think anybody here has run the tests with the intel compiler. On the other hand, this bug was already present in the code. Technically, if no bugs are introduced in the code and only new functionality is added, then the results of the regtests should not change when running in non-debug code, that is why the regtests are there and my changes did not show any errors. On the contrary, if a bug is introduced (or fixed), the regtests should capture it unless there is no test for the configuration that is affected. Glad to fix old bugs anyway (three of them this time), and that we are slowly adding new tests!

**Comment by ukmo-ccbunney** [comment]
> 
> 
> regtest passed ! thanks Juan.
> I think that it would be better for the next PR if you could run the regtests matrix with intel_debug to detect possible bugs which are not seen by gfortran

Hi @mickaelaccensi - we had some issues here with libraries on our Cray HPC that stopped me from compiling with the Intel compiler last time I tried. However, I will look into it again to see if I can get it working. Thanks for sorting out the review. 👍

**Comment by ukmo-juan-castillo** [comment]
@ukmo-ccbunney found some problems with the oasis regtests, so a revision of the branch has lead to new changes that now work for both the oasis and multi tests. All regtests writing a multi restart will be affected by the bug fix.

The changes will be directly added to the staging_jan2021 branch.

**Pull request merged**
