### PR TITLE
Dealing with issue #397

### LINKED ISSUE #397: floating overflow on regtest ww3_tp2.8
**Describe the bug**
a floating overflow error appears when running the regtest ww3_tp2.8.
this is due to the call of the subroutine INTERP in ww3_prnc

**To Reproduce**
./bin/run_test -o netcdf -N -c datarmor_mpt_debug ../model ww3_tp2.8

**Expected behavior**
I suspect the muliplication of 2*fillvalue*fillvalue produce a too large value

**Screenshots**
   Screen output routed to  regtests/ww3_tp2.8/work/ww3_prnc.out
forrtl: error (72): floating overflow
Image              PC                Routine            Line        Source             
ww3_prnc           00000000009B8D9E  Unknown               Unknown  Unknown
libpthread-2.19.s  00007FFFEB3E6870  Unknown               Unknown  Unknown
ww3_prnc           0000000000484D28  MAIN__                   1648  ww3_prnc.F90
ww3_prnc           000000000040BF1E  Unknown               Unknown  Unknown
libc-2.19.so       00007FFFEB050B25  __libc_start_main     Unknown  Unknown
ww3_prnc           000000000040BE29  Unknown               Unknown  Unknown
./bin/run_test: line 1253:  6951 Aborted                 $runprog $path_e/$prog > $ofile

line 1648 in ww3_prnc.F90 if : 
                CALL INTERP(MXM, MYM, XC**2+YC**2, IX21, IX22,         &
                               IY21, IY22, RD11, RD12, RD21, RD22,     &
                               2.0*FILLVALUE*FILLVALUE, A3)

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# Pull Request Summary
Fix float overflow when calling the interp subroutine

## Description
The interp subroutine was giving an overflow error. This happened when it was called with a large value of the fillvalue parameter of the function. What has been done here is calling the interp routine with the original value of the fillvalue variable, and to do so the vector that is being interpolated in the routine is passed to the interp routine in a way such that the original fill value of the variables making up the vector variable is preserved.

### Issue(s) addressed
* Is there an issue associated with this development (bug fix, enhancement, new feature)?   
YES

- fixes #397
- fixes noaa-emc/ww3/issues/397

### Check list  
* Is your feature branch up to date with the authoritative repository (NOAA/develop)?
YES
* Make sure you have checked the [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop), [checklist for a developer submitting to develop](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop) and [updating version number](https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-updating-version-number)
DONE
* Reviewers: @mickaelaccensi @ukmo-ccbunney 

### Testing
* How were these changes tested?
Running the ww3_tp2.18 regtest in debug mode
* Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
Covered, but only if compiling in debug mode - no errors are thrown otherwise
* If a new feature was added, was a new regression test added?
NO
* Have regression tests been run?
YES, but only those affected (ww3_tp2.18)
* Which compiler / HPC you used to run the regression tests in the PR? 
CrayXC40 at the Met Office with the GNU compiler with and without debug options
* Please provide the summary output of matrix.comp (_matrix.Diff.out_, _matrixCompFull.out_ and _matrixCompSummary.out_):    
[matrix.zip](https://github.com/ukmo-waves/WW3/files/6592552/matrix.zip)

Please indicate the expected changes in the outputs ([excluding the known list of non-identical tests](https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results)).

Changes in results are observed but they are supposedly already present for ww3_tp2.18 - if not, they are justified as we are implementing a bug fix.

### CODE REVIEW

**Comment by ukmo-juan-castillo** [comment]
One possible improvement would be exchanging the order of the interp calls that were modified, so that we do not have to calculate first a square root and then do the square of the resulting value - we will only need to calculate the square root at the end.

**Comment by ukmo-ccbunney** [comment]
> 
> 
> One possible improvement would be exchanging the order of the interp calls that were modified, so that we do not have to calculate first a square root and then do the square of the resulting value - we will only need to calculate the square root at the end.

I think the two calculations are subtly different - A2 is the interpolated value of the magnitude `interp (sqrt (x^2 + y^2)`), whereas A3 is the square root of the interpolated sum of the powers `sqrt (interp (x^2 + y^2) )` 

So the results could be different if the weights `RDxx` are not equal.

**Comment by ukmo-juan-castillo** [comment]
I agree, but right now what we are doing is:

TMP = sqrt(x^2+y^2)
A2 = interp(TMP)

TMP=TMP*TMP
A3 = interp(TMP)

What I propose to do is changing the order of interpolation so that less calculations are performed on TMP, as with the previous code we first make a square root of a variable (x^2+y^2) and then we square the result to obtain again the variable - it is more efficient to use the variable first and then do the square root:

TMP=(X^2+Y^2)
A3 = interp(TMP)

TMP = SQRT(TMP)
A2 = interp(TMP)

**Comment by ukmo-ccbunney** [comment]
> 
> 
> I agree, but right now what we are doing is:
> 
> TMP = sqrt(x^2+y^2)
> A2 = interp(TMP)
> 
> TMP=TMP*TMP
> A3 = interp(TMP)
> 
> What I propose to do is changing the order of interpolation so that less calculations are performed on TMP, as with the previous code we first make a square root of a variable (x^2+y^2) and then we square the result to obtain again the variable - it is more efficient to use the variable first and then do the square root:
> 
> TMP=(X^2+Y^2)
> A3 = interp(TMP)
> 
> TMP = SQRT(TMP)
> A2 = interp(TMP)

Ah yes - I see where you are coming from.
Yes - that would work, but I wonder what actual impact it would have. I guess if the arrays get very large, there maybe a saving on runtime. However, seeing as you will already have a new XTEMP array as part of this bugfix, you may as well do it!

**Comment by ukmo-juan-castillo** [comment]
I implemented the small improvement discussed in the previous comments, and tested it against the previous version of the code. I obtained the same results apart from the known 'BAD POINT' differences.

I also run the new code in debug mode and received a new error in the ww3_tp2.18 regtest in the program ww3_prtide. I checked that I obtain the same error when running the latest version of the develop branch:

> Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

> Backtrace for this error:

> Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

> Backtrace for this error:
#0  0x6705DD in _gfortrani_backtrace at backtrace.c:258
#1  0x65A780 in _gfortrani_backtrace_handler at compile_options.c:129
#2  0x6598FF in __pause_nocancel
#3  0x67D6AD in _amd_raise_fp_exc at libm_special.c:37
#4  0x67D845 in _powf_special at libm_special.c:1109
#5  0x67CE25 in fastpowf at w_powf.S:437
#0  0x6705DD in _gfortrani_backtrace at backtrace.c:258
#1  0x65A780 in _gfortrani_backtrace_handler at compile_options.c:129
#2  0x6598FF in __pause_nocancel
#3  0x650C97 in __w3tidemd_MOD_setvuf_fast at w3tidemd.F90:626 (discriminator 16)
#4  0x40AC19 in w3prtide at ww3_prtide.F90:582 (discriminator 8)

I discussed this error with @ukmo-ccbunney  and we agreed that this must be related to issue #225, so nothing will be done here as it will be fixed in that issue.

**Review by mickaelaccensi — APPROVED** [review]
thanks Juan, it solved the problem.
the only thing I had to do to make it work was to add missing arguments MXM,MYM to INTERP function in ww3_prnc.ftn at line 1829 :
```
                    CALL INTERP(MXM, MYM, YC, JX21, JX22, JY21, JY22, XD11, XD12,&
                                             XD21, XD22, FILLVALUE, FA)
```

but I think this is assigned to another issue and PR

**Comment by ukmo-juan-castillo** [comment]
Thank you for the review, and for finding the problem at line 1829, indeed there are missing parameters to the INTERP call. I see the fix for the faulty line is included in issue #407, which as already been merged.

**Pull request merged**
